id: IADA807C6
legacy_id: P006604
ocr_import_info:
  bdrc_scan_id: W2PD17620
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T16:01:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:11:49.609318+00:00'
last_modified: 2022-08-27 19:12:26.188389
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD17620
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD17620
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: 四川藏学研究
statistics:
  ocr_word_mean_confidence_index: 0.9458536760992527
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I4PD4253:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4253
      total_pages: 428
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD4253.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9458536760992527
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
