id: IADA807C6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:04:08+00:00'
last_modified: '2022-06-08T05:34:22.224556+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17620
  title: '四川藏学研究

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0B51:
      image_group_id: I4PD4253
      title: ''
      total_pages: 428
      order: 1
      base_file: 0B51.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
