id: P006604
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17620
  title: '四川藏学研究

    '
  author: ''
  volumes:
    156646cf4b714124aaea45b24758723e:
      image_group_id: I4PD4253
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
