id: P006604
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:09:49.623160
source_metadata:
  id: bdr:W2PD17620
  title: '四川藏学研究

    '
  author: ''
  volumes:
    156646cf4b714124aaea45b24758723e:
      image_group_id: I4PD4253
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
